### PR TITLE
Build: Enforce consistent line endings

### PR DESCRIPTION
**Pull request by erikkemperman**
C.f., gulpjs/vinyl-fs#269

### CODE REVIEW

**Comment by erikkemperman** [comment]
This is erroring (only) on `stable` due to leaks... Should I fix the test config or do we want to use mocha/expect here like the other repos?

Same thing for async-once, conventional-changelog-gulp, and undertaker-registry.

**Comment by erikkemperman** [comment]
This is erroring (only) on `stable` due to leaks... Should I fix the test config or do we want to use mocha/expect here like the other repos?

Same thing for async-once, conventional-changelog-gulp, and undertaker-registry.

**Comment by phated** [comment]
@erikkemperman I also just caught some of these old repo setups (with lab/code) and have been switching them to mocha/expect like the up-to-date repos.  I started to switch away from lab because they dropped node <4 support and this leak thing started showing up in the old version we were forced to use.

**Comment by erikkemperman** [comment]
All right, I guess I'll just leave these newline PRs as is then, for rebase after that swap.

**Comment by phated** [comment]
Rebase broke this but I cherry-picked it into master.  Thanks @erikkemperman

**Pull request closed without merging**
